export { animate } from "./animate/index"
export { animateStyle } from "./animate/animate-style"
export { timeline } from "./timeline/index"
export { stagger } from "./utils/stagger"
export { spring } from "./js/easing/spring/index"
export { glide } from "./js/easing/glide/index"
export { style } from "./animate/style"

export { getAnimationData } from "./animate/data"
export { getStyleName } from "./animate/utils/get-style-name"
export { getOptions } from "./animate/utils/options"
export { createMotionState, mountedStates } from "./state/index"
export { createStyles } from "./animate/utils/style-object"
export { createStyleString } from "./animate/utils/style-string"
export { defaults } from "./animate/utils/defaults"
export { isCustomEasing } from "./animate/utils/easing"

export * from "./state/types"
export * from "./animate/types"
